name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: '8.3'
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run tests
        run: ./vendor/bin/phpunit --configuration phpunit.xml
